volumes: 
  foodfetcher-data:
services:
  foodfetcher:
    build: .
    restart: unless-stopped
    environment:
      # this needs to be specified here because the file structure in the
      # container does not align with the dev environment
      - DATABASE_URL=file:/app/data/database.db
      # this is needed so that nextAuth doesn't send the
      # user to a bad port or internal address. Very 
      # sub-optimal and annoying, tbh
      - NEXTAUTH_URL=https://foodfetcher.fufufuzz.cc
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      #- HOSTNAME=foodfetcher.fufufuzz.cc
      #- NETWORK=0.0.0.0
    #ports:
    #  - '3000:3000'
    volumes:
      - "foodfetcher-data:/app/data/"
      - "./.env.local:/app/.env.local:ro"